Disable QA step in CI workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,29 +11,29 @@ jobs:
       - uses: actions/checkout@v3
       - uses: actions/dependency-review-action@v3
 
-  qa:
-    name: QA
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-go@v4
-        with:
-          go-version-file: go.mod
-      - uses: arduino/setup-task@v1
-        with:
-          version: 3.x
-      - name: Check Formatting
-        run: test -z "$(go fmt ./...)" || echo "Formatting check failed."
-      - name: Test
-        run: task test
-      - name: Vet
-        run: go vet ./...
-      - name: Lint
-        uses: dominikh/staticcheck-action@v1.3.0
-        with:
-          install-go: false
-      - name: Build
-        run: task build
+  # qa:
+  #   name: QA
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: actions/setup-go@v4
+  #       with:
+  #         go-version-file: go.mod
+  #     - uses: arduino/setup-task@v1
+  #       with:
+  #         version: 3.x
+  #     - name: Check Formatting
+  #       run: test -z "$(go fmt ./...)" || echo "Formatting check failed."
+  #     - name: Test
+  #       run: task test
+  #     - name: Vet
+  #       run: go vet ./...
+  #     - name: Lint
+  #       uses: dominikh/staticcheck-action@v1.3.0
+  #       with:
+  #         install-go: false
+  #     - name: Build
+  #       run: task build
 
   terraform_validate_plan_report:
     name: Validate and plan terraform
